pull_request_rules:
  - name: automatic merge when CI passes and reviews
    conditions:
      - base=master
      - '#approved-reviews-by>=1'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      - 'status-success=WIP'
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
      delete_head_branch:

  - name: delete head branch when closed
    conditions:
      - closed
    actions:
      delete_head_branch:
