coverage:
  range: '80...100'
  precision: 2
  status:
    default:
      enabled: yes
      target: 90
      threshold: 10
    patch:
      default:
        enabled: no
        if_not_found: success
