version: '3.7'

# ssl dependent by traefik (https://github.com/ridi/traefik)
services:
  books:
    image: node:10
    container_name: books
    volumes:
      - type: bind
        source: .
        target: /books
      - type: volume
        source: node_modules
        target: /books/node_modules
        volume:
          nocopy: true
    working_dir: /books
    init: true
    environment:
      ENVIRONMENT: local
      NEXT_TELEMETRY_DISABLED: '1'
    command: >
      sh -c "yarn install --frozen-lockfile &&
             node ./server/server.js"
volumes:
  node_modules:
