version: '3.7'
services:
  books:
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${EXTERNAL_NETWORK:-ridi}'
      - 'traefik.frontend.rule=Host:books.local.ridi.io'
    networks:
      traefik:
        aliases:
          - books
    environment:
      - ASSET_PREFIX=https://books.local.ridi.io
      - PORT=8081
    ports:
      - 8081
networks:
  traefik:
    external:
      name: ${EXTERNAL_NETWORK:-ridi}
