version: '3.7'

# ssl dependent by traefik (https://github.com/ridi/traefik)
services:
  store-web:
    image: node:8.10
    build:
      dockerfile: $PWD/provisioning/local/Dockerfile
      context: ./
    container_name: store-web
    volumes:
      - .:/store-web
    working_dir: /store-web
    environment:
      ENVIRONMENT: local
    command: ['make', 'docker-start-local']
