service: books

package:
  exclude:
    - node_modules/**
    - '*.js.map'
    - .cache
    - coverage/**
    - static/**
    - src/tests/**
    - secrets.json
    - yarn.lock
    - provisioning/**
    - cypress/**
    - src/**
    - tsconfig.json
    - static/**

provider:
  name: aws
  runtime: nodejs8.10
  NODE_PATH: './:/opt/node_modules'
  region: ${self:custom.secrets.REGION}
  stage: ${opt:stage, 'development'}
  # CloudFormation Name
  stackName: books-sls-${opt:stage, 'development'}
  deploymentBucket:
    name: books.sls.${opt:stage, 'development'}.${self:provider.region}.deploys
  # serverSideEncryption: AES256
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

layers:
  nodeModules:
    path: node_modules
    compatibleRuntimes:
      - nodejs8.10
    description: sentry + next.js + emotion + ts + redux node_modules
    package:
      exclude:
        - node_modules/.cache/**
        - node_modules/@types/**
        - node_modules/serverless/**
        - node_modules/codecov/**
        - node_modules/aws-sdk/**
        - node_modules/prettier/**

functions:
  server:
    path: /
    handler: server/index.handler
    layers:
      - { Ref: NodeModulesLambdaLayer }
    warmup:
      enabled:
        - development
        - staging
        - production
    events:
      - cors: true
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-s3-sync
  - serverless-plugin-warmup

custom:
  warmup:
    enabled: true
    cleanFolder: false
    memorySize: 256
    timeout: 20
    prewarm: true
    concurrency: 1
  s3Sync:
    - bucketName: books.sls.${opt:stage, 'development'}.${self:provider.region}.deploys
      bucketPrefix: static/ # optional
      localDir: static/ # required
    - bucketName: books.sls.${opt:stage, 'development'}.${self:provider.region}.deploys
      bucketPrefix: _next/ # optional
      localDir: build/
      params: # optional
        - '*.js':
            CacheControl: 'public, max-age=31536000'

  stage: ${opt:stage, 'development'}
  secrets: ${file(secrets.json)}
  domains:
    production:
      lambda: ${self:custom.secrets.PROD_DOMAIN}
      static: ${self:custom.secrets.PROD_STATIC_DOMAIN}
    staging:
      lambda: ${self:custom.secrets.STAGING_DOMAIN}
      static: ${self:custom.secrets.STAGING_STATIC_DOMAIN}
    development:
      lambda: ${self:custom.secrets.DEV_DOMAIN}
      static: ${self:custom.secrets.DEV_STATIC_DOMAIN}

  apigwBinary:
    types:
      - '*/*'

resources:
  Resources:
    StaticBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: books.sls.${opt:stage, 'development'}.${self:provider.region}.deploys
        PolicyDocument:
          Statement:
            - Sid: 'AllowPublicRead'
              Action:
                - 's3:GetObject'
              Effect: 'Allow'
              Resource:
                - arn:aws:s3:::books.sls.${opt:stage,'development'}.${self:provider.region}.deploys/_next/*
                - arn:aws:s3:::books.sls.${opt:stage,'development'}.${self:provider.region}.deploys/static/*
              Principal: '*'
#    LambdaDNSRecord:
#      Type: AWS::Route53::RecordSet
#      Properties:
#        HostedZoneName: store.ridi.io.
#        Name: ${self:custom.domains.${self:custom.stage}.lambda}
#        Type: A
#        AliasTarget:
#          DNSName: d37y2lgp9u1ne4.cloudfront.net.
#          HostedZoneId: Z2FDTNDATAQYW2
#    StaticDNSRecord:
#      Type: AWS::Route53::RecordSet
#      Properties:
#        HostedZoneName: store.ridi.io.
#        Name: ${self:custom.domains.${self:custom.stage}.static}
#        Type: A
#        AliasTarget:
#          DNSName: d1dpwi79ahko80.cloudfront.net.
#          HostedZoneId: Z2FDTNDATAQYW2
# https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
