service: store-web

package:
  exclude:
    - node_modules/.cache/**
    - .cache
    - yarn.lock

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.secrets.REGION}
  stage: ${opt:stage, 'development'}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  server:
    path: /
    handler: server/index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
# Proxy Resource:
# https://docs.aws.amazon.com/ko_kr/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-domain-manager

# Serverless.js Custom Domain 사용하지 않을 경우 다음 이슈 확인
# https://github.com/Vadorequest/serverless-with-next#known-issues
custom:
  stage: ${opt:stage, 'development'}
  secrets: ${file(secrets.json)}
  domains:
    production: ${self:custom.secrets.PROD_DOMAIN}
    staging: ${self:custom.secrets.STAGING_DOMAIN}
    development: ${self:custom.secrets.DEV_DOMAIN}

  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: ''
    stage: ${opt:stage, 'development'}
    certificateName: ${self:custom.secrets.ACM_NAME}
    createRoute53Record: true
    endpointType: 'regional'
