name: Google Lighthouse

on:
  push:
    branches:
      - chore/add-lighthouserc.json
      - master
  schedule:
    - cron: '*/5 * * * *'

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Run Lighhouse CI
        run: |
          npm install -g @lhci/cli
          lhci collect --numberOfRuns=5 --url=https://ridibooks.com

      - name: Save Results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files
